run:
  concurrency: 4

linters-settings:
  dupl:
    threshold: 200
  funlen:
    lines: 100
    statements: 50
  gocritic:
    disabled-checks:
      - appendAssign
  goimports:
    local-prefixes: github.com/slavamuravey

linters:
  presets:
    - style
    - bugs
    - complexity
    - format
    - performance
    - unused
  disable-all: false
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - goimports
    - goheader
    - golint
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    - nestif
    - nlreturn
    - noctx
    - nolintlint
    - prealloc
    - rowserrcheck
    - scopelint
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - testpackage
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wrapcheck
    - whitespace
    - wsl
  disable:
    - gci
    - gofumpt
    - exhaustivestruct

service:
  golangci-lint-version: 1.32.2 # use the fixed version to not introduce new linters unexpectedly
